use_frameworks!

platform :ios, '9.0'

target 'ZJHBase_Example' do
  pod 'ZJHBase', :path => '../'
  pod 'ZJHCommon', :path => '../../ZJHCommon'
  pod 'ZJHMe', :path => '../../ZJHMe'
  pod 'ZJHHome', :path => '../../ZJHHome'

  target 'ZJHBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
