use_frameworks!

platform :ios, '9.0'

target 'ZJHBase_Example' do
  pod 'ZJHBase', :path => '../'

  target 'ZJHBase_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
